CREATE TRIGGER inc_na_s1 AFTER INSERT ON public.usa_seller_1_not_approved FOR EACH ROW EXECUTE FUNCTION trg_inc_not_approved_s1();
CREATE TRIGGER inc_na_s2 AFTER INSERT ON public.usa_seller_2_not_approved FOR EACH ROW EXECUTE FUNCTION trg_inc_na_s2();
CREATE TRIGGER inc_na_s3 AFTER INSERT ON public.usa_seller_3_not_approved FOR EACH ROW EXECUTE FUNCTION trg_inc_na_s3();
CREATE TRIGGER inc_na_s4 AFTER INSERT ON public.usa_seller_4_not_approved FOR EACH ROW EXECUTE FUNCTION trg_inc_na_s4();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.copy_progress_timestamps FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER sync_purchases_origin_trigger BEFORE INSERT OR UPDATE ON public.usa_purchases FOR EACH ROW EXECUTE FUNCTION sync_usa_purchases_origin();
CREATE TRIGGER trg_auto_distribute_1 AFTER INSERT ON public.flipkart_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION flipkart_auto_distribute_to_funnels();
CREATE TRIGGER trg_auto_distribute_2 AFTER INSERT ON public.flipkart_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION flipkart_auto_distribute_to_funnels();
CREATE TRIGGER trg_auto_distribute_3 AFTER INSERT ON public.flipkart_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION flipkart_auto_distribute_to_funnels();
CREATE TRIGGER trg_auto_distribute_4 AFTER INSERT ON public.flipkart_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION flipkart_auto_distribute_to_funnels();
CREATE TRIGGER trg_auto_distribute_5 AFTER INSERT ON public.flipkart_brand_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION flipkart_auto_distribute_to_funnels();
CREATE TRIGGER trg_auto_distribute_6 AFTER INSERT ON public.flipkart_brand_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION flipkart_auto_distribute_to_funnels();
CREATE TRIGGER trg_distribute_seller_1 AFTER INSERT ON public.usa_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION distribute_seller_products();
CREATE TRIGGER trg_distribute_seller_2 AFTER INSERT ON public.usa_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION distribute_seller_products();
CREATE TRIGGER trg_distribute_seller_3 AFTER INSERT ON public.usa_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION distribute_seller_products();
CREATE TRIGGER trg_distribute_seller_4 AFTER INSERT ON public.usa_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION distribute_seller_products();
CREATE TRIGGER trg_flipkart_brand_checking_recalc_1 AFTER INSERT OR DELETE ON public.flipkart_brand_checking_seller_1 FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_brand_checking_recalc();
CREATE TRIGGER trg_flipkart_brand_checking_recalc_2 AFTER INSERT OR DELETE ON public.flipkart_brand_checking_seller_2 FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_brand_checking_recalc();
CREATE TRIGGER trg_flipkart_brand_checking_recalc_3 AFTER INSERT OR DELETE ON public.flipkart_brand_checking_seller_3 FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_brand_checking_recalc();
CREATE TRIGGER trg_flipkart_brand_checking_recalc_4 AFTER INSERT OR DELETE ON public.flipkart_brand_checking_seller_4 FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_brand_checking_recalc();
CREATE TRIGGER trg_flipkart_brand_checking_recalc_5 AFTER INSERT OR DELETE ON public.flipkart_brand_checking_seller_5 FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_brand_checking_recalc();
CREATE TRIGGER trg_flipkart_brand_checking_recalc_6 AFTER INSERT OR DELETE ON public.flipkart_brand_checking_seller_6 FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_brand_checking_recalc();
CREATE TRIGGER trg_flipkart_checking_to_brand_1 AFTER INSERT ON public.flipkart_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION flipkart_move_checking_to_brand_checking();
CREATE TRIGGER trg_flipkart_checking_to_brand_2 AFTER INSERT ON public.flipkart_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION flipkart_move_checking_to_brand_checking();
CREATE TRIGGER trg_flipkart_checking_to_brand_3 AFTER INSERT ON public.flipkart_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION flipkart_move_checking_to_brand_checking();
CREATE TRIGGER trg_flipkart_checking_to_brand_4 AFTER INSERT ON public.flipkart_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION flipkart_move_checking_to_brand_checking();
CREATE TRIGGER trg_flipkart_checking_to_brand_5 AFTER INSERT ON public.flipkart_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION flipkart_move_checking_to_brand_checking();
CREATE TRIGGER trg_flipkart_checking_to_brand_6 AFTER INSERT ON public.flipkart_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION flipkart_move_checking_to_brand_checking();
CREATE TRIGGER trg_flipkart_distribute_1 AFTER INSERT ON public.flipkart_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION flipkart_distribute_seller_products();
CREATE TRIGGER trg_flipkart_distribute_2 AFTER INSERT ON public.flipkart_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION flipkart_distribute_seller_products();
CREATE TRIGGER trg_flipkart_distribute_3 AFTER INSERT ON public.flipkart_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION flipkart_distribute_seller_products();
CREATE TRIGGER trg_flipkart_distribute_4 AFTER INSERT ON public.flipkart_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION flipkart_distribute_seller_products();
CREATE TRIGGER trg_flipkart_distribute_5 AFTER INSERT ON public.flipkart_brand_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION flipkart_distribute_seller_products();
CREATE TRIGGER trg_flipkart_distribute_6 AFTER INSERT ON public.flipkart_brand_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION flipkart_distribute_seller_products();
CREATE TRIGGER trg_flipkart_distribute_to_brand_checking AFTER INSERT ON public.flipkart_master_sellers FOR EACH ROW EXECUTE FUNCTION flipkart_distribute_to_brand_checking_sellers();
CREATE TRIGGER trg_flipkart_gen_link_1 BEFORE INSERT ON public.flipkart_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_gen_link_2 BEFORE INSERT ON public.flipkart_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_gen_link_3 BEFORE INSERT ON public.flipkart_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_gen_link_4 BEFORE INSERT ON public.flipkart_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_gen_link_5 BEFORE INSERT ON public.flipkart_brand_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_gen_link_6 BEFORE INSERT ON public.flipkart_brand_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_generate_amz_link_seller_1 BEFORE INSERT ON public.flipkart_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_generate_amz_link_seller_2 BEFORE INSERT ON public.flipkart_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_generate_amz_link_seller_3 BEFORE INSERT ON public.flipkart_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_generate_amz_link_seller_4 BEFORE INSERT ON public.flipkart_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_generate_amz_link_seller_5 BEFORE INSERT ON public.flipkart_brand_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_generate_amz_link_seller_6 BEFORE INSERT ON public.flipkart_brand_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION generate_flipkart_amz_link();
CREATE TRIGGER trg_flipkart_master_update_sync AFTER UPDATE OF remark, monthly_unit ON public.flipkart_master_sellers FOR EACH ROW EXECUTE FUNCTION flipkart_sync_master_update_to_sellers();
CREATE TRIGGER trg_flipkart_not_approved_1 AFTER INSERT OR DELETE ON public.flipkart_seller_1_not_approved FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_not_approved_recalc();
CREATE TRIGGER trg_flipkart_not_approved_2 AFTER INSERT OR DELETE ON public.flipkart_seller_2_not_approved FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_not_approved_recalc();
CREATE TRIGGER trg_flipkart_not_approved_3 AFTER INSERT OR DELETE ON public.flipkart_seller_3_not_approved FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_not_approved_recalc();
CREATE TRIGGER trg_flipkart_not_approved_4 AFTER INSERT OR DELETE ON public.flipkart_seller_4_not_approved FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_not_approved_recalc();
CREATE TRIGGER trg_flipkart_not_approved_5 AFTER INSERT OR DELETE ON public.flipkart_seller_5_not_approved FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_not_approved_recalc();
CREATE TRIGGER trg_flipkart_not_approved_6 AFTER INSERT OR DELETE ON public.flipkart_seller_6_not_approved FOR EACH STATEMENT EXECUTE FUNCTION flipkart_handle_not_approved_recalc();
CREATE TRIGGER trg_flipkart_rebalance_1 AFTER UPDATE OF monthly_unit, remark ON public.flipkart_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION flipkart_rebalance_funnel_on_update();
CREATE TRIGGER trg_flipkart_rebalance_2 AFTER UPDATE OF monthly_unit, remark ON public.flipkart_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION flipkart_rebalance_funnel_on_update();
CREATE TRIGGER trg_flipkart_rebalance_3 AFTER UPDATE OF monthly_unit, remark ON public.flipkart_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION flipkart_rebalance_funnel_on_update();
CREATE TRIGGER trg_flipkart_rebalance_4 AFTER UPDATE OF monthly_unit, remark ON public.flipkart_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION flipkart_rebalance_funnel_on_update();
CREATE TRIGGER trg_flipkart_rebalance_5 AFTER UPDATE OF monthly_unit, remark ON public.flipkart_brand_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION flipkart_rebalance_funnel_on_update();
CREATE TRIGGER trg_flipkart_rebalance_6 AFTER UPDATE OF monthly_unit, remark ON public.flipkart_brand_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION flipkart_rebalance_funnel_on_update();
CREATE TRIGGER trg_flipkart_restore_distribution AFTER INSERT ON public.flipkart_master_sellers FOR EACH ROW EXECUTE FUNCTION flipkart_restore_old_distribution();
CREATE TRIGGER trg_flipkart_validation_approval_changes AFTER INSERT OR DELETE OR UPDATE ON public.flipkart_validation_main_file FOR EACH ROW EXECUTE FUNCTION flipkart_handle_validation_recalc();
CREATE TRIGGER trg_generate_amz_link_seller_1 BEFORE INSERT ON public.usa_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION generate_amz_link();
CREATE TRIGGER trg_generate_amz_link_seller_2 BEFORE INSERT ON public.usa_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION generate_amz_link();
CREATE TRIGGER trg_generate_amz_link_seller_3 BEFORE INSERT ON public.usa_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION generate_amz_link();
CREATE TRIGGER trg_generate_amz_link_seller_4 BEFORE INSERT ON public.usa_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION generate_amz_link();
CREATE TRIGGER trg_india_distribute_seller_1 AFTER INSERT ON public.india_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION india_distribute_seller_products();
CREATE TRIGGER trg_india_distribute_seller_2 AFTER INSERT ON public.india_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION india_distribute_seller_products();
CREATE TRIGGER trg_india_distribute_seller_3 AFTER INSERT ON public.india_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION india_distribute_seller_products();
CREATE TRIGGER trg_india_distribute_seller_4 AFTER INSERT ON public.india_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION india_distribute_seller_products();
CREATE TRIGGER trg_india_distribute_seller_5 AFTER INSERT ON public.india_brand_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION india_distribute_seller_products();
CREATE TRIGGER trg_india_distribute_seller_6 AFTER INSERT ON public.india_brand_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION india_distribute_seller_products();
CREATE TRIGGER trg_india_distribute_to_brand_checking AFTER INSERT ON public.india_master_sellers FOR EACH ROW EXECUTE FUNCTION india_distribute_to_brand_checking_sellers();
CREATE TRIGGER trg_india_master_update_sync AFTER UPDATE OF remark, monthly_unit ON public.india_master_sellers FOR EACH ROW EXECUTE FUNCTION india_sync_master_update_to_sellers();
CREATE TRIGGER trg_india_seller_1_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.india_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION india_rebalance_funnel_on_update();
CREATE TRIGGER trg_india_seller_2_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.india_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION india_rebalance_funnel_on_update();
CREATE TRIGGER trg_india_seller_3_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.india_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION india_rebalance_funnel_on_update();
CREATE TRIGGER trg_india_seller_4_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.india_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION india_rebalance_funnel_on_update();
CREATE TRIGGER trg_india_seller_5_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.india_brand_checking_seller_5 FOR EACH ROW EXECUTE FUNCTION india_rebalance_funnel_on_update();
CREATE TRIGGER trg_india_seller_6_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.india_brand_checking_seller_6 FOR EACH ROW EXECUTE FUNCTION india_rebalance_funnel_on_update();
CREATE TRIGGER trg_india_validation_refresh_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_validation_main_file FOR EACH ROW EXECUTE FUNCTION refresh_all_sellers_from_validation();
CREATE TRIGGER trg_not_approved_1 AFTER INSERT OR DELETE ON public.usa_seller_1_not_approved FOR EACH ROW EXECUTE FUNCTION trg_handle_not_approved_recalc();
CREATE TRIGGER trg_not_approved_2 AFTER INSERT OR DELETE ON public.usa_seller_2_not_approved FOR EACH ROW EXECUTE FUNCTION trg_handle_not_approved_recalc();
CREATE TRIGGER trg_not_approved_3 AFTER INSERT OR DELETE ON public.usa_seller_3_not_approved FOR EACH ROW EXECUTE FUNCTION trg_handle_not_approved_recalc();
CREATE TRIGGER trg_not_approved_4 AFTER INSERT OR DELETE ON public.usa_seller_4_not_approved FOR EACH ROW EXECUTE FUNCTION trg_handle_not_approved_recalc();
CREATE TRIGGER trg_reset_s1 AFTER DELETE OR TRUNCATE ON public.usa_seller_1_high_demand FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_reset_s1_na AFTER DELETE OR TRUNCATE ON public.usa_seller_1_not_approved FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_reset_s2 AFTER DELETE OR TRUNCATE ON public.usa_seller_2_high_demand FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_reset_s2_na AFTER DELETE OR TRUNCATE ON public.usa_seller_2_not_approved FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_reset_s3 AFTER DELETE OR TRUNCATE ON public.usa_seller_3_high_demand FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_reset_s3_na AFTER DELETE OR TRUNCATE ON public.usa_seller_3_not_approved FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_reset_s4 AFTER DELETE OR TRUNCATE ON public.usa_seller_4_high_demand FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_reset_s4_na AFTER DELETE OR TRUNCATE ON public.usa_seller_4_not_approved FOR EACH STATEMENT EXECUTE FUNCTION call_reset_after_change();
CREATE TRIGGER trg_s1_dp_progress AFTER INSERT OR DELETE ON public.india_seller_1_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_1();
CREATE TRIGGER trg_s1_hd_progress AFTER INSERT OR DELETE ON public.india_seller_1_high_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_1();
CREATE TRIGGER trg_s1_ld_progress AFTER INSERT OR DELETE ON public.india_seller_1_low_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_1();
CREATE TRIGGER trg_s1_na_progress AFTER INSERT OR DELETE ON public.india_seller_1_not_approved FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_1();
CREATE TRIGGER trg_s2_dp_progress AFTER INSERT OR DELETE ON public.india_seller_2_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_2();
CREATE TRIGGER trg_s2_hd_progress AFTER INSERT OR DELETE ON public.india_seller_2_high_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_2();
CREATE TRIGGER trg_s2_ld_progress AFTER INSERT OR DELETE ON public.india_seller_2_low_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_2();
CREATE TRIGGER trg_s2_na_progress AFTER INSERT OR DELETE ON public.india_seller_2_not_approved FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_2();
CREATE TRIGGER trg_s3_dp_progress AFTER INSERT OR DELETE ON public.india_seller_3_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_3();
CREATE TRIGGER trg_s3_hd_progress AFTER INSERT OR DELETE ON public.india_seller_3_high_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_3();
CREATE TRIGGER trg_s3_ld_progress AFTER INSERT OR DELETE ON public.india_seller_3_low_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_3();
CREATE TRIGGER trg_s3_na_progress AFTER INSERT OR DELETE ON public.india_seller_3_not_approved FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_3();
CREATE TRIGGER trg_s4_dp_progress AFTER INSERT OR DELETE ON public.india_seller_4_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_4();
CREATE TRIGGER trg_s4_hd_progress AFTER INSERT OR DELETE ON public.india_seller_4_high_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_4();
CREATE TRIGGER trg_s4_ld_progress AFTER INSERT OR DELETE ON public.india_seller_4_low_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_4();
CREATE TRIGGER trg_s4_na_progress AFTER INSERT OR DELETE ON public.india_seller_4_not_approved FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_4();
CREATE TRIGGER trg_s5_dp_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_5_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_5();
CREATE TRIGGER trg_s5_hd_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_5_high_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_5();
CREATE TRIGGER trg_s5_ld_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_5_low_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_5();
CREATE TRIGGER trg_s5_na_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_5_not_approved FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_5();
CREATE TRIGGER trg_s6_dp_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_6_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_6();
CREATE TRIGGER trg_s6_hd_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_6_high_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_6();
CREATE TRIGGER trg_s6_ld_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_6_low_demand FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_6();
CREATE TRIGGER trg_s6_na_progress AFTER INSERT OR DELETE OR UPDATE ON public.india_seller_6_not_approved FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_india_progress_seller_6();
CREATE TRIGGER trg_uae_distribute_seller_1_products AFTER INSERT ON public.uae_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION uae_distribute_seller_products();
CREATE TRIGGER trg_uae_distribute_seller_2_products AFTER INSERT ON public.uae_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION uae_distribute_seller_products();
CREATE TRIGGER trg_uae_distribute_seller_3_products AFTER INSERT ON public.uae_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION uae_distribute_seller_products();
CREATE TRIGGER trg_uae_distribute_seller_4_products AFTER INSERT ON public.uae_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION uae_distribute_seller_products();
CREATE TRIGGER trg_uae_distribute_to_brand_checking AFTER INSERT ON public.uae_master_sellers FOR EACH ROW EXECUTE FUNCTION uae_distribute_to_brand_checking_sellers();
CREATE TRIGGER trg_uae_generate_amz_link_seller_1 BEFORE INSERT ON public.uae_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION generate_uae_amz_link();
CREATE TRIGGER trg_uae_generate_amz_link_seller_2 BEFORE INSERT ON public.uae_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION generate_uae_amz_link();
CREATE TRIGGER trg_uae_generate_amz_link_seller_3 BEFORE INSERT ON public.uae_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION generate_uae_amz_link();
CREATE TRIGGER trg_uae_generate_amz_link_seller_4 BEFORE INSERT ON public.uae_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION generate_uae_amz_link();
CREATE TRIGGER trg_uae_master_update_sync AFTER UPDATE OF remark, monthly_unit ON public.uae_master_sellers FOR EACH ROW EXECUTE FUNCTION uae_sync_master_update_to_sellers();
CREATE TRIGGER trg_uae_s1_dp AFTER INSERT OR DELETE ON public.uae_seller_1_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_1();
CREATE TRIGGER trg_uae_s1_hd AFTER INSERT OR DELETE ON public.uae_seller_1_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_1();
CREATE TRIGGER trg_uae_s1_ld AFTER INSERT OR DELETE ON public.uae_seller_1_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_1();
CREATE TRIGGER trg_uae_s1_na AFTER INSERT OR DELETE ON public.uae_seller_1_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_1();
CREATE TRIGGER trg_uae_s2_dp AFTER INSERT OR DELETE ON public.uae_seller_2_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_2();
CREATE TRIGGER trg_uae_s2_hd AFTER INSERT OR DELETE ON public.uae_seller_2_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_2();
CREATE TRIGGER trg_uae_s2_ld AFTER INSERT OR DELETE ON public.uae_seller_2_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_2();
CREATE TRIGGER trg_uae_s2_na AFTER INSERT OR DELETE ON public.uae_seller_2_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_2();
CREATE TRIGGER trg_uae_s3_dp AFTER INSERT OR DELETE ON public.uae_seller_3_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_3();
CREATE TRIGGER trg_uae_s3_hd AFTER INSERT OR DELETE ON public.uae_seller_3_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_3();
CREATE TRIGGER trg_uae_s3_ld AFTER INSERT OR DELETE ON public.uae_seller_3_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_3();
CREATE TRIGGER trg_uae_s3_na AFTER INSERT OR DELETE ON public.uae_seller_3_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_3();
CREATE TRIGGER trg_uae_s4_dp AFTER INSERT OR DELETE ON public.uae_seller_4_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_4();
CREATE TRIGGER trg_uae_s4_hd AFTER INSERT OR DELETE ON public.uae_seller_4_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_4();
CREATE TRIGGER trg_uae_s4_ld AFTER INSERT OR DELETE ON public.uae_seller_4_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_4();
CREATE TRIGGER trg_uae_s4_na AFTER INSERT OR DELETE ON public.uae_seller_4_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uae_trg_recalc_seller_4();
CREATE TRIGGER trg_uae_seller_1_update_funnel AFTER UPDATE OF monthly_unit ON public.uae_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION uae_rebalance_funnel_on_update();
CREATE TRIGGER trg_uae_seller_2_update_funnel AFTER UPDATE OF monthly_unit ON public.uae_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION uae_rebalance_funnel_on_update();
CREATE TRIGGER trg_uae_seller_3_update_funnel AFTER UPDATE OF monthly_unit ON public.uae_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION uae_rebalance_funnel_on_update();
CREATE TRIGGER trg_uae_seller_4_update_funnel AFTER UPDATE OF monthly_unit ON public.uae_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION uae_rebalance_funnel_on_update();
CREATE TRIGGER trg_uae_validation_approval AFTER INSERT OR DELETE OR UPDATE ON public.uae_validation_main_file FOR EACH ROW EXECUTE FUNCTION uae_trg_validation_approval();
CREATE TRIGGER trg_uk_distribute_seller_1_products AFTER INSERT ON public.uk_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION uk_distribute_seller_products();
CREATE TRIGGER trg_uk_distribute_seller_2_products AFTER INSERT ON public.uk_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION uk_distribute_seller_products();
CREATE TRIGGER trg_uk_distribute_seller_3_products AFTER INSERT ON public.uk_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION uk_distribute_seller_products();
CREATE TRIGGER trg_uk_distribute_seller_4_products AFTER INSERT ON public.uk_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION uk_distribute_seller_products();
CREATE TRIGGER trg_uk_distribute_to_brand_checking AFTER INSERT ON public.uk_master_sellers FOR EACH ROW EXECUTE FUNCTION uk_distribute_to_brand_checking_sellers();
CREATE TRIGGER trg_uk_generate_amz_link_seller_1 BEFORE INSERT ON public.uk_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION generate_uk_amz_link();
CREATE TRIGGER trg_uk_generate_amz_link_seller_2 BEFORE INSERT ON public.uk_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION generate_uk_amz_link();
CREATE TRIGGER trg_uk_generate_amz_link_seller_3 BEFORE INSERT ON public.uk_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION generate_uk_amz_link();
CREATE TRIGGER trg_uk_generate_amz_link_seller_4 BEFORE INSERT ON public.uk_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION generate_uk_amz_link();
CREATE TRIGGER trg_uk_master_update_sync AFTER UPDATE OF remark, monthly_unit ON public.uk_master_sellers FOR EACH ROW EXECUTE FUNCTION uk_sync_master_update_to_sellers();
CREATE TRIGGER trg_uk_s1_dp AFTER INSERT OR DELETE ON public.uk_seller_1_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_1();
CREATE TRIGGER trg_uk_s1_hd AFTER INSERT OR DELETE ON public.uk_seller_1_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_1();
CREATE TRIGGER trg_uk_s1_ld AFTER INSERT OR DELETE ON public.uk_seller_1_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_1();
CREATE TRIGGER trg_uk_s1_na AFTER INSERT OR DELETE ON public.uk_seller_1_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_1();
CREATE TRIGGER trg_uk_s2_dp AFTER INSERT OR DELETE ON public.uk_seller_2_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_2();
CREATE TRIGGER trg_uk_s2_hd AFTER INSERT OR DELETE ON public.uk_seller_2_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_2();
CREATE TRIGGER trg_uk_s2_ld AFTER INSERT OR DELETE ON public.uk_seller_2_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_2();
CREATE TRIGGER trg_uk_s2_na AFTER INSERT OR DELETE ON public.uk_seller_2_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_2();
CREATE TRIGGER trg_uk_s3_dp AFTER INSERT OR DELETE ON public.uk_seller_3_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_3();
CREATE TRIGGER trg_uk_s3_hd AFTER INSERT OR DELETE ON public.uk_seller_3_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_3();
CREATE TRIGGER trg_uk_s3_ld AFTER INSERT OR DELETE ON public.uk_seller_3_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_3();
CREATE TRIGGER trg_uk_s3_na AFTER INSERT OR DELETE ON public.uk_seller_3_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_3();
CREATE TRIGGER trg_uk_s4_dp AFTER INSERT OR DELETE ON public.uk_seller_4_dropshipping FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_4();
CREATE TRIGGER trg_uk_s4_hd AFTER INSERT OR DELETE ON public.uk_seller_4_high_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_4();
CREATE TRIGGER trg_uk_s4_ld AFTER INSERT OR DELETE ON public.uk_seller_4_low_demand FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_4();
CREATE TRIGGER trg_uk_s4_na AFTER INSERT OR DELETE ON public.uk_seller_4_not_approved FOR EACH STATEMENT EXECUTE FUNCTION uk_trg_recalc_seller_4();
CREATE TRIGGER trg_uk_seller_1_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.uk_brand_checking_seller_1 FOR EACH ROW EXECUTE FUNCTION uk_rebalance_funnel_on_update();
CREATE TRIGGER trg_uk_seller_2_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.uk_brand_checking_seller_2 FOR EACH ROW EXECUTE FUNCTION uk_rebalance_funnel_on_update();
CREATE TRIGGER trg_uk_seller_3_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.uk_brand_checking_seller_3 FOR EACH ROW EXECUTE FUNCTION uk_rebalance_funnel_on_update();
CREATE TRIGGER trg_uk_seller_4_update_funnel AFTER UPDATE OF monthly_unit, remark ON public.uk_brand_checking_seller_4 FOR EACH ROW EXECUTE FUNCTION uk_rebalance_funnel_on_update();
CREATE TRIGGER trg_uk_validation_approval AFTER INSERT OR DELETE OR UPDATE ON public.uk_validation_main_file FOR EACH ROW EXECUTE FUNCTION uk_trg_validation_approval();
CREATE TRIGGER trg_update_constants_timestamp BEFORE UPDATE ON public.india_validation_constants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_usa_seller_1_golden_aura_movement_history AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_1_golden_aura_movement_history FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_usa_seller_1_reject AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_1_reject FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_usa_seller_2_reject AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_2_reject FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_usa_seller_2_rudra_retail_movement_history AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_2_rudra_retail_movement_history FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_usa_seller_3_reject AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_3_reject FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_usa_seller_3_ubeauty_movement_history AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_3_ubeauty_movement_history FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_usa_seller_4_reject AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_4_reject FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_usa_seller_4_velvet_vista_movement_history AFTER INSERT OR DELETE OR UPDATE ON public.usa_seller_4_velvet_vista_movement_history FOR EACH STATEMENT EXECUTE FUNCTION trigger_recalc_from_table();
CREATE TRIGGER trg_validation_approval_changes AFTER INSERT OR DELETE ON public.usa_validation_main_file FOR EACH ROW EXECUTE FUNCTION trg_handle_validation_approval();
CREATE TRIGGER trigger_distribute_to_sellers AFTER INSERT OR UPDATE ON public.usa_master_sellers FOR EACH ROW EXECUTE FUNCTION distribute_to_brand_checking_sellers();
CREATE TRIGGER update_admin_constants_timestamp BEFORE UPDATE ON public.uk_admin_validation_constants FOR EACH ROW EXECUTE FUNCTION update_admin_constants_updated_at();
CREATE TRIGGER update_admin_constants_timestamp BEFORE UPDATE ON public.usa_admin_validation_constants FOR EACH ROW EXECUTE FUNCTION update_admin_constants_updated_at();
CREATE TRIGGER update_usa_purchases_updated_at BEFORE UPDATE ON public.usa_purchases FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
