CREATE TRIGGER trg_bc_dist AFTER INSERT ON public.brand_checking FOR EACH ROW EXECUTE FUNCTION unified_distribute_to_seller_products();
CREATE TRIGGER trg_bc_gen_amz BEFORE INSERT ON public.brand_checking FOR EACH ROW EXECUTE FUNCTION unified_generate_amz_link();
CREATE TRIGGER trg_bc_rebal AFTER UPDATE OF monthly_unit, remark ON public.brand_checking FOR EACH ROW EXECUTE FUNCTION unified_rebalance_funnel_on_update();
CREATE TRIGGER trg_bc_recalc AFTER INSERT OR DELETE ON public.brand_checking FOR EACH ROW EXECUTE FUNCTION trg_brand_checking_recalc();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.copy_progress_timestamps FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER trg_flipkart_master_dist AFTER INSERT ON public.flipkart_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_distribute_to_brand_checking();
CREATE TRIGGER trg_flipkart_master_sync AFTER UPDATE OF remark, monthly_unit ON public.flipkart_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_sync_master_update();
CREATE TRIGGER trg_flipkart_val_r AFTER INSERT OR DELETE OR UPDATE ON public.flipkart_validation_main_file FOR EACH ROW EXECUTE FUNCTION generic_validation_recalc();
CREATE TRIGGER trg_india_master_dist AFTER INSERT ON public.india_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_distribute_to_brand_checking();
CREATE TRIGGER trg_india_master_sync AFTER UPDATE OF remark, monthly_unit ON public.india_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_sync_master_update();
CREATE TRIGGER trg_update_constants_timestamp BEFORE UPDATE ON public.india_validation_constants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_auto_usa_link BEFORE INSERT OR UPDATE OF asin, usa_link ON public.india_validation_main_file FOR EACH ROW EXECUTE FUNCTION auto_populate_usa_link();
CREATE TRIGGER trg_india_val_r AFTER INSERT OR DELETE OR UPDATE ON public.india_validation_main_file FOR EACH ROW EXECUTE FUNCTION generic_validation_recalc();
CREATE TRIGGER trg_sp_recalc AFTER INSERT OR DELETE OR UPDATE OF product_status ON public.seller_products FOR EACH ROW EXECUTE FUNCTION trg_seller_products_recalc();
CREATE TRIGGER trg_uae_master_dist AFTER INSERT ON public.uae_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_distribute_to_brand_checking();
CREATE TRIGGER trg_uae_master_sync AFTER UPDATE OF remark, monthly_unit ON public.uae_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_sync_master_update();
CREATE TRIGGER trg_uae_val_r AFTER INSERT OR DELETE OR UPDATE ON public.uae_validation_main_file FOR EACH ROW EXECUTE FUNCTION generic_validation_recalc();
CREATE TRIGGER update_admin_constants_timestamp BEFORE UPDATE ON public.uk_admin_validation_constants FOR EACH ROW EXECUTE FUNCTION update_admin_constants_updated_at();
CREATE TRIGGER trg_uk_master_dist AFTER INSERT ON public.uk_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_distribute_to_brand_checking();
CREATE TRIGGER trg_uk_master_sync AFTER UPDATE OF remark, monthly_unit ON public.uk_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_sync_master_update();
CREATE TRIGGER trg_uk_val_r AFTER INSERT OR DELETE OR UPDATE ON public.uk_validation_main_file FOR EACH ROW EXECUTE FUNCTION generic_validation_recalc();
CREATE TRIGGER update_admin_constants_timestamp BEFORE UPDATE ON public.usa_admin_validation_constants FOR EACH ROW EXECUTE FUNCTION update_admin_constants_updated_at();
CREATE TRIGGER trg_usa_master_dist AFTER INSERT OR UPDATE ON public.usa_master_sellers FOR EACH ROW EXECUTE FUNCTION generic_distribute_to_brand_checking();
CREATE TRIGGER sync_purchases_origin_trigger BEFORE INSERT OR UPDATE ON public.usa_purchases FOR EACH ROW EXECUTE FUNCTION sync_usa_purchases_origin();
CREATE TRIGGER update_usa_purchases_updated_at BEFORE UPDATE ON public.usa_purchases FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_usa_val_r AFTER INSERT OR DELETE ON public.usa_validation_main_file FOR EACH ROW EXECUTE FUNCTION generic_validation_recalc();
